name: ðŸ›‘ Stop Staging

on:
  workflow_dispatch: # Permet le bouton manuel dans l'onglet Actions

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Container via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 1702
          script: |
            cd /home/erickdesmet/STAGING_SAAS/FitMyCV/landing
            docker compose -f docker-compose.staging.yml down
            echo "Staging arrÃªtÃ©."
